"""empty message

Revision ID: 9e7f2516ca00
Revises: 85092d6f4b92
Create Date: 2023-05-01 20:13:28.742850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7f2516ca00'
down_revision = '85092d6f4b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction',
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('minimum_height', sa.Integer(), nullable=False),
    sa.Column('duration_in_minutes', sa.Integer(), nullable=False),
    sa.Column('location_section', sa.String(length=10), nullable=False),
    sa.CheckConstraint("location_section IN ('Lot A', 'Lot B', 'Lot C', 'Lot D')"),
    sa.CheckConstraint("status IN ('open', 'closed', 'under maintenance')"),
    sa.CheckConstraint("type IN ('roller coaster', 'water ride', 'dark ride', 'kid ride')"),
    sa.PrimaryKeyConstraint('attraction_id')
    )
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('menu_item', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("category IN ('Food stall', 'Ice cream parlor', 'Restaurant', 'Gift Shop', 'Apparels')"),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('visitor',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('street', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=30), nullable=False),
    sa.Column('cell_number', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('visitor_type', sa.String(length=10), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.CheckConstraint("visitor_type IN ('Individual', 'Group', 'Member', 'Student')"),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name_on_card', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('exp_date', sa.Date(), nullable=False),
    sa.Column('cvv_number', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("payment_method IN ('Cash', 'Credit', 'Debit Card')"),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('visitor_attraction',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.attraction_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('visitor_id', 'attraction_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('parking',
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(length=50), nullable=False),
    sa.Column('spot_number', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('parking_id')
    )
    op.create_table('show',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('wheelchair_accessible', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('drama', 'musical', 'comedy', 'horror', 'adventure')"),
    sa.CheckConstraint("wheelchair_accessible IN ('Yes', 'No')"),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('ticket_method', sa.String(length=6), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("ticket_method IN ('Online', 'Onsite')"),
    sa.CheckConstraint("type IN ('Child', 'Adult', 'Senior', 'Member')"),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('visitor_show',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.show_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.visitor_id'], ),
    sa.PrimaryKeyConstraint('visitor_id', 'show_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_show')
    op.drop_table('ticket')
    op.drop_table('show')
    op.drop_table('parking')
    op.drop_table('order')
    op.drop_table('visitor_attraction')
    op.drop_table('payment')
    op.drop_table('visitor')
    op.drop_table('store')
    op.drop_table('attraction')
    # ### end Alembic commands ###
