"""empty message

Revision ID: c1dee5a99b17
Revises: ca6537cd4191
Create Date: 2023-05-03 20:05:40.599813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1dee5a99b17'
down_revision = 'ca6537cd4191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_constraint('show_ibfk_1', type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('show_ibfk_1', 'payment', ['payment_id'], ['payment_id'])

    # ### end Alembic commands ###
